### ISSUE TITLE
tokenized_ds = load_from_disk(data_config.data_path).  The data_path cannot be found

### ISSUE THREAD

**Issue by supermancmk** [KbsdJames/MATH-Minos#2]
https://github.com/KbsdJames/MATH-Minos/blob/81a69e9ef9c365c1fbcb823f8efb50815e083cb0/RM/process_reward_modeling_pointwise.py#L428

Thank you very much for your great work! When I load the Math-Shepherd dataset, the following error occurs: `tokenized_ds = load_from_disk(data_config.data_path)` - it says the file cannot be found. Could you provide the post-processed file?

**Comment by KbsdJames** [comment]
Thank you for your feedback. The `tokenized_ds` is the data from math-shepherd that has been processed according to the ORM or PRM format and then tokenized using the tokenizer. We will provide the data processing code and the training data soon.

**Comment by KbsdJames** [comment]
> https://github.com/KbsdJames/MATH-Minos/blob/81a69e9ef9c365c1fbcb823f8efb50815e083cb0/RM/process_reward_modeling_pointwise.py#L428
> 
> Thank you very much for your great work! When I load the Math-Shepherd dataset, the following error occurs: `tokenized_ds = load_from_disk(data_config.data_path)` - it says the file cannot be found. Could you provide the post-processed file?

Thank you for your feedback. The tokenized_ds is the data from math-shepherd that has been processed according to the ORM or PRM format and then tokenized using the tokenizer. We will provide the data processing code and the training data soon.

**Comment by KbsdJames** [comment]
> https://github.com/KbsdJames/MATH-Minos/blob/81a69e9ef9c365c1fbcb823f8efb50815e083cb0/RM/process_reward_modeling_pointwise.py#L428
> 
> Thank you very much for your great work! When I load the Math-Shepherd dataset, the following error occurs: `tokenized_ds = load_from_disk(data_config.data_path)` - it says the file cannot be found. Could you provide the post-processed file?

Thank you for your feedback. The `tokenized_ds` is the data from Math-Shepherd that has been processed according to the ORM or PRM format and then tokenized using the tokenizer. We will provide the data processing code and the training data soon.

**Comment by KbsdJames** [comment]
> https://github.com/KbsdJames/MATH-Minos/blob/81a69e9ef9c365c1fbcb823f8efb50815e083cb0/RM/process_reward_modeling_pointwise.py#L428
> 
> Thank you very much for your great work! When I load the Math-Shepherd dataset, the following error occurs: `tokenized_ds = load_from_disk(data_config.data_path)` - it says the file cannot be found. Could you provide the post-processed file?

Hello, we have provided the data for ORM and PRM training. You can find it in the Readme. Please check it. Thank you again for your feedback.

**Comment by supermancmk** [comment]
Thank you very much! Good job
